Traceback (most recent call last):
  File "C:\Users\pmarshal\Anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\pmarshal\Anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\pmarshal\Anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\pmarshal\Anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\pmarshal\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\pmarshal\Anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\pmarshal\Anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\pmarshal\Anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# generate watershed map
catchments = ['capilano', 'seymour']
parameters = ['swe']
for parameter in parameters:
    outputfile = os.path.join(outputfolder, f'map_{parameter}.png')
    rep.watershed_map(api, catchments, parameter, outputfile, width=7, height=7)
    rep.insert_image(outputfile, table=0, row=0, col=0, width=5, height=5)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [2][0m, in [0;36m<cell line: 4>[1;34m()[0m
[0;32m      3[0m parameters [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mswe[39m[38;5;124m'[39m]
[0;32m      4[0m [38;5;28;01mfor[39;00m parameter [38;5;129;01min[39;00m parameters:
[1;32m----> 5[0m     outputfile [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mjoin([43moutputfolder[49m, [38;5;124mf[39m[38;5;124m'[39m[38;5;124mmap_[39m[38;5;132;01m{[39;00mparameter[38;5;132;01m}[39;00m[38;5;124m.png[39m[38;5;124m'[39m)
[0;32m      6[0m     rep[38;5;241m.[39mwatershed_map(api, catchments, parameter, outputfile, width[38;5;241m=[39m[38;5;241m7[39m, height[38;5;241m=[39m[38;5;241m7[39m)
[0;32m      7[0m     rep[38;5;241m.[39minsert_image(outputfile, table[38;5;241m=[39m[38;5;241m0[39m, row[38;5;241m=[39m[38;5;241m0[39m, col[38;5;241m=[39m[38;5;241m0[39m, width[38;5;241m=[39m[38;5;241m5[39m, height[38;5;241m=[39m[38;5;241m5[39m)

[1;31mNameError[0m: name 'outputfolder' is not defined
NameError: name 'outputfolder' is not defined

